import { Geist, Geist_Mono } from "next/font/google";

import SideNavbar from "./components/Shared/SideNavbar";

import type { Metadata } from "next";

import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <div className="layout-container">
          <SideNavbar/>

          <section className="main-content">
            {/* Insert Top Bar Here */}
          </section>

          <main>{children}</main>
        </div>
        </body>
    </html>
  );
}
